apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mural.fullname" . }}
  labels:
    {{- include "mural.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # /api vai para a API; o resto para o front. Como o front também sabe
          # fazer proxy de /api, ambos os caminhos funcionam — aqui deixamos o
          # roteamento explícito no Ingress para o /api não depender do nginx do front.
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "mural.apiService" . }}
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mural.fullname" . }}-web
                port:
                  number: 80
