apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mural.fullname" . }}-db
  labels:
    {{- include "mural.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  # A API só recebe a connection string por aqui (Secret), nunca hardcoded.
  DATABASE_URL: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "mural.postgresHost" . }}:5432/{{ .Values.postgres.database }}?sslmode=disable"
